services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:80' # Пробрасываем порт 80 контейнера на 3000 порт хоста
        container_name: react-app
        restart: unless-stopped # Автоматически перезапускаем контейнер если он падает
