version: '3.8' # Версия схемы Docker Compose

services:
    react-app:
        build:
            context: . # Указываем текущую директорию как контекст сборки
            dockerfile: Dockerfile # Указываем имя Dockerfile
        ports:
            - '80:80' # Пробрасываем порт 3000 контейнера на порт 3000 хоста
        container_name: react-app # Имя контейнера
        restart: unless-stopped # Автоматически перезапускать контейнер, если он падает
